# Generated by Django 4.2.20 on 2025-08-10 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_count', models.IntegerField(default=0, verbose_name='上传文档数')),
                ('modification_count', models.IntegerField(default=0, verbose_name='修改文档数')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='成功率(%)')),
                ('upload_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='上传评分')),
                ('modification_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='修改评分')),
                ('quality_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='质量评分')),
                ('efficiency_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='效率评分')),
                ('collaboration_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='协作评分')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='总分')),
                ('weighted_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='加权总分')),
                ('comments', models.TextField(blank=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
            ],
            options={
                'verbose_name': '员工绩效',
                'verbose_name_plural': '员工绩效',
                'ordering': ['-period__start_date', '-weighted_score'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评估周期',
                'verbose_name_plural': '评估周期',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('metric_type', models.CharField(choices=[('upload', '文档上传'), ('modification', '文档修改'), ('quality', '工作质量'), ('efficiency', '工作效率'), ('collaboration', '团队协作')], max_length=20, verbose_name='指标类型')),
                ('description', models.TextField(blank=True, verbose_name='指标描述')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)], verbose_name='权重')),
                ('max_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='最高分值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '绩效指标',
                'verbose_name_plural': '绩效指标',
                'ordering': ['metric_type', 'weight'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('evaluate', '评估'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='adminpanel.employeeperformance', verbose_name='绩效记录')),
            ],
            options={
                'verbose_name': '绩效日志',
                'verbose_name_plural': '绩效日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employeeperformance',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='adminpanel.evaluationperiod', verbose_name='评估周期'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together={('employee', 'period')},
        ),
    ]
