# Generated by Django 4.2.20 on 2025-08-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='employeeperformance',
            name='period',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='performance',
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.DeleteModel(
            name='EmployeePerformance',
        ),
        migrations.DeleteModel(
            name='EvaluationPeriod',
        ),
        migrations.DeleteModel(
            name='PerformanceLog',
        ),
    ]
