# Generated by Django 4.2.20 on 2025-04-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='feedback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='feedback_app.feedback'),
        ),
    ]
