# Generated by Django 4.2.20 on 2025-07-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_feedback_options_alter_record_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback_app.record'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['record', 'username'], name='feedback_record__74e103_idx'),
        ),
    ]
