# Generated by Django 4.2.20 on 2025-08-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0004_documenttask_is_active_feedback_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='documenttask',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
        migrations.AddField(
            model_name='documenttask',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
