# Generated by Django 4.2.20 on 2025-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_changelog_comments_changelog_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
