# Generated by Django 4.2.20 on 2025-08-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0006_alter_record_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
