# Generated by Django 4.2.20 on 2025-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0007_alter_feedback_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documenttask',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
