# Generated by Django 4.2.20 on 2025-09-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback_app', '0008_changelog_state_documenttask_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
